-- SQL Script for CheckInn Hotel Reservation System Schema

-----------------------------------
-- 1. Table: users
-- Stores all registered user accounts.
-----------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15),
    -- Stores the password HASH generated by the Java application
    password VARCHAR(255) NOT NULL,
    -- Added a timestamp for audit/tracking, good practice
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-----------------------------------
-- 2. Table: hotels
-- Stores information about the hotels available in the system.
-----------------------------------
CREATE TABLE IF NOT EXISTS hotels (
    hotel_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255)
);

-----------------------------------
-- 3. Table: rooms
-- Stores details of individual rooms.
-- NOTE: isAvailable is dynamic and determined by reservation logic,
--       so it is NOT stored in the DB (only static room attributes are).
-----------------------------------
CREATE TABLE IF NOT EXISTS rooms (
    room_id INT AUTO_INCREMENT PRIMARY KEY,
    hotel_id INT NOT NULL,
    room_no INT NOT NULL,
    type VARCHAR(50) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,

    FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id),
    -- Ensures a room number is unique within a single hotel
    UNIQUE (hotel_id, room_no)
);

-----------------------------------
-- 4. Table: reservations
-- Stores main reservation records.
-- NOTE: This structure matches the Reservation class directly.
-----------------------------------
CREATE TABLE IF NOT EXISTS reservations (
    res_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    room_id INT NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    -- Total is the GROSS cost (including GST)
    total DECIMAL(10, 2) NOT NULL,
    booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (room_id) REFERENCES rooms(room_id)
);


-----------------------------------
-- 5. Initial Seed Data (Optional but Recommended)
-----------------------------------

-- Insert Sample User
-- Password should be updated manually or via the app's registration/login process
INSERT INTO users (name, email, phone, password) VALUES
('Admin User', 'admin@checkinn.com', '9876543210', 'INITIAL_HASH_GOES_HERE');

-- Insert Sample Hotels
INSERT INTO hotels (name, address) VALUES
('Grand View Residency', '123 Main Street, City Center'),
('The Heritage Inn', '45 Park Avenue, Old Town');

-- Insert Sample Rooms (Prices are GROSS, including GST)
-- Assuming Hotel ID 1
INSERT INTO rooms (hotel_id, room_no, type, price) VALUES
(1, 101, 'Single', 1500.00),
(1, 102, 'Single', 1500.00),
(1, 201, 'Double', 3500.00),
(1, 202, 'Double', 3500.00),
(1, 301, 'Suite', 7000.00);

-- Assuming Hotel ID 2
INSERT INTO rooms (hotel_id, room_no, type, price) VALUES
(2, 10, 'Double', 2500.00),
(2, 11, 'Double', 2500.00),


-- Sample User insertion (with 3 Hotels)
-- Insert 20 New Users
INSERT INTO users (name, email, phone, password) VALUES
('Luke Skywalker', 'luke.skywalker@smail.com', '555-4501', 'password123'),
('Leia Organa', 'leia.organa@smail.com', '555-4502', 'password123'),
('Lando Calrissian', 'lando.calrissian@smail.com', '555-4503', 'password123'),
('Cal Kestis', 'cal.kestis@grandbespin.com', '555-4504', 'password123'),
('Din Djarin', 'din.djarin@grandbespin.com', '555-4505', 'password123'),
('Jango Fett', 'jango.fett@grandbespin.com', '555-4506', 'password123'),
('Kleya Marki', 'kleya.marki@grandbespin.com', '555-4507', 'password123'),
('Cassian Andor', 'cassian.andor@grandbespin.com', '555-4508', 'password123'),
('Liana Hallik', 'liana.hallik@grandbespin.com', '555-4509', 'password123'),

('Jean Grey', 'jean.grey@xaviermanor.com', '555-4510', 'fireandlifeincarnate'),
('Warren Worthington', 'warren.worthington@xaviermanor.com', '555-4511', 'password123'),
('Robert Drake', 'robert.drake@xaviermanor.com', '555-4512', 'password123'),
('Henry McCoy', 'henry.mccoy@xaviermanor.com', '555-4513', 'ohmystarsandgarters'),
('Max Eisenhardt', 'max.eisenhardt@xaviermanor.com', '555-4514', 'anya123'),
('Charles Xavier', 'charles.xavier@xaviermanor.com', '555-4515', 'iamright'),

('Sirius Black', 'sirius.black@grimauldplace.com', '555-4516', 'harry123'),
('Severus Snape', 'severus.snape@grimauldplace.com', '555-4517', 'lilly123'),
('Kingsley Shacklebolt', 'kingsley.shacklebolt@grimauldplace.com', '555-4518', 'dumbledoregotstyle'),
('Albus Dumbledore', 'albus.dumbledore@grimauldplace.com', '555-4519', 'sherbetlemons'),
('Minerva McGonagall', 'minerva.mcgonagall@grimauldplace.com', '555-4520', 'biscuit123');